### ISSUE TITLE
[enhancement] Webpack chunks

### ISSUE THREAD

**Issue by bartlomiejzuber** [preactjs/compressed-size-action#13]
This action doesn't work well when build produces chunks with generated hash.

![image](https://user-images.githubusercontent.com/9931428/75153344-7c4e8980-570b-11ea-9220-2289e3cee1a7.png)

Please make it possible to provide stripHashRegex which will be passed to stripHash function of https://github.com/GoogleChromeLabs/size-plugin .

Will try to provide PR with change with this.

**Comment by developit** [comment]
That would be a lovely improvement! This action uses `size-plugin-core`, which should be able to perform the hash stripping, so my guess is that this is actually a bug.

**Comment by moretti** [comment]
One workaround is to use `process.env.GITHUB_ACTIONS` in `webpack.config.js` to determine when the build task runs from Github and use an alternative naming convention for chunks, eg. 
```.js
output: {
    chunkFilename: process.env.GITHUB_ACTIONS
        ? '[name].js'
        : '[id].js',
}
```
(see https://webpack.js.org/configuration/output/#outputchunkfilename)

**Comment by developit** [comment]
Custom `strip-hash` support was released in [v2](https://github.com/preactjs/compressed-size-action/releases/tag/v2). The hashes shown in this issue can be normalized using the following configuration:

```yaml
    strip-hash: "\\.(\\w{8})\\.chunk\\.js$"
```

This will convert `build/static/js/5034h92h.chunk.js` to `build/static/js/********.chunk.js`.
