### ISSUE TITLE
git checkout fails when switching to base commit

### ISSUE THREAD

**Issue by schliflo** [preactjs/compressed-size-action#17]
I am getting the following error:

![Screenshot 2020-03-13 at 20 41 24](https://user-images.githubusercontent.com/9881672/76654446-3dbe2900-656b-11ea-8d96-6a504e52a13f.png)

A possible fix probably is using `git reset --hard ${baseRef}` instead of `git checkout ${baseRef}` here:
https://github.com/preactjs/compressed-size-action/blob/9754acd0ee298ba98deebeed0f8a0eae25e0f356/action.js#L91

Is there a way for me to easily test this fix without publishing my own fork as an action? I'd be happy to create a PR, but I don't see a way to test this properly...

**Comment by developit** [comment]
Testing Github Actions is pretty much a manual process at this point. If you could PR that change, I'll test it out locally and verify. It seems like a very reasonable and safe change, since the container filesystem isn't persisted anywhere.

**Comment by schliflo** [comment]
Sure, I'll get right to it.
