### ISSUE TITLE
Doesn't find build artifacts in nested folder in dist

### ISSUE THREAD

**Issue by ricokahler** [preactjs/compressed-size-action#23]
I have a bit of an edge case setup where:

1. it's a monorepo, building multiple packages into `dist` at once
2. each package's build artifact goes into `/dist/package-1/index.esm.js`

It seems like `compressed-size-action` isn't finding the `/dist/package-1/index.esm.js`. Looking into the code here, it seems like [the default glob pattern](https://github.com/preactjs/compressed-size-action/blob/d85e1f35d37b4df8a5f29c2f06209d70a0578702/action.js#L54) (i.e. `**/dist/**/*.js`) should match my files.

Below is a screenshot of my test in [globster](https://globster.xyz/) where the highlighted files are the matched files.

![image](https://user-images.githubusercontent.com/10551026/81035538-6840aa00-8e69-11ea-8a5d-39b96b8a7ab5.png)

If it helps, [you can see the result my CI run here](https://github.com/ricokahler/react-style-system/pull/56). 

Hope that helps fix this issue and thanks a bunch for this awesome action!

**Comment by kroofy** [comment]
Could you try changing to v2? That fixed it for me.

```yaml
- uses: preactjs/compressed-size-action@v2
```

**Comment by ricokahler** [comment]
@kroofy [I gave that a go](https://github.com/ricokahler/react-style-system/pull/90/files#diff-23e7bc4f32f5fd1923c7abd2a6ad130aR9). [Still nothin'](https://github.com/ricokahler/react-style-system/pull/90#issuecomment-629519844)

**Comment by ricokahler** [comment]
Oh wow, I just realized I updated `checkout` instead of `compressed-size` in my github workflow file. I actually updated to v2 and it's working now. 🤦‍♀️

**Comment by kroofy** [comment]
Glad to hear it worked out!
