### ISSUE TITLE
Document missing inputs?

### ISSUE THREAD

**Issue by brandonweiss** [preactjs/compressed-size-action#27]
Hey! I was reading through the README and couldn’t quite figure out how this action worked… there didn’t seem to be any configuration about where to look for the output of the build. I thought maybe it automagically figured it out by only comparing untracked file (not checked in to Git) Then I read through the source and found there are `pattern` and `exclude` inputs.

Is there a reason those aren’t documented in `action.yml` and the README? 🤔

**Comment by brandonweiss** [comment]
Actually after testing it out it seems I can’t use the `pattern` or `exclude` inputs because they’re not defined in the `action.yml` 🤔 Does that mean this action can’t be used unless your bundle happens to be located in a “dist” folder?

**Comment by brandonweiss** [comment]
Oh, I just discovered #24 🤦‍♂️

**Comment by developit** [comment]
Fixed in the latest v2 (v2.0.1)!
