### ISSUE TITLE
Enabling tracking of non-js files

### ISSUE THREAD

**Issue by Allcharles** [preactjs/compressed-size-action#29]
Currently it appears this compress-size-action only contains the ability to track changes in .js files. Is it possible to expand this to track all changed build file types? Or at least provide a regex or list which identifies all filetypes to track? For example, a generic angular project build file will contain a mixture of js, css, json, and html files (along with a few other minor extension types).

**Comment by developit** [comment]
This is already supported - you can pass any file type in the `pattern` option:

```diff
name: Compressed Size

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
+       pattern: "build/**/*.{css,js,json,html}"
```
