### ISSUE TITLE
Better support for monorepos

### ISSUE THREAD

**Issue by Meemaw** [preactjs/compressed-size-action#37]
In a monorepo one might use multiple actions on a PR to report changes on different modules.

- If using comments, each of those actions will override/"update" the previous comment.
- If using "use-check" the behaviour is wrong as well

Proposed solution:
- Introduce an input that will dedup those comments (e.g. label or something). One could pass label="App 1", label="App2"  (this could also be displayed in the final markdown for better UI/UX) which would additionally be used to dedup the comments.

**Comment by developit** [comment]
Wouldn't it be better to have a single action calculate and size diffs for all files in the monorepo?

**Comment by frassinier** [comment]
Agreed with @developit,
if you use Lerna, for example, you just have to include all packages using `pattern`
```yml
          pattern: './packages/*/dist/*.{js,css}'
```

**Comment by rschristian** [comment]
Support for multiple comments is tracked by #81
