### ISSUE TITLE
Comments are not stripped from compressed files

### ISSUE THREAD

**Issue by necolas** [preactjs/compressed-size-action#39]
JavaScript comments are not removed from the built files and contribute to reported file size. I think comments should be stripped to provide realistic data that reflects what a production build would do.

**Comment by necolas** [comment]
I opened an issue against the `size-plugin-core` module as it looks like that is where the feature is missing - https://github.com/kuldeepkeshwar/size-plugin-core/issues/8

**Comment by developit** [comment]
This would likely have to be an option that is disabled by default, since it requires parsing the JS. That'll be slow, right now file files aren't even loaded into memory.

**Comment by necolas** [comment]
FWIW I use a fork of this action with a fork of the size plugin - https://github.com/necolas/compressed-size-plugin/commit/082eb2c4cb56548aedfa6e967aa52507e569ccad

**Comment by rschristian** [comment]
Closing, as the better solution here would be to feed the intended output into this action. If you production builds strip comments, then do that and provide the result to compressed-size here.
