### ISSUE TITLE
Release v2.1.0 is not on the marketplace

### ISSUE THREAD

**Issue by hamstercat** [preactjs/compressed-size-action#57]
I've tried using this action in my repo, but it seems like the latest version (v2.1.0) is not available on the marketplace. This is what I got in my GitHub workflow:

```
Error: Unable to resolve action `preactjs/compressed-size-action@v2.1.0`, unable to find version `v2.1.0`
```

It seems to be missing from GitHub's marketplace page too:

<img width="1047" alt="Screen Shot 2021-04-04 at 11 11 14 AM" src="https://user-images.githubusercontent.com/829897/113513214-81008680-9536-11eb-8c34-087b8c9c98a9.png">

I'm guessing there's just a step missing since the release already exists in this repo?

**Comment by developit** [comment]
I believe it was just published as `v2`.

**Comment by hamstercat** [comment]
Thanks for the quick answer! I hadn't tried it but you're right, v2 does have the updated `cwd` option so it's the latest already. Will update to that one.
