### ISSUE TITLE
only supports being run on "[pull_request]"

### ISSUE THREAD

**Issue by gavinsharp** [preactjs/compressed-size-action#6]
Thanks for the cool action!

I tried adding it on my existing push-triggered workflow, and got a confusing error on my first try:
```
Run preactjs/compressed-size-action@v1
  with:
    repo-token: ***
    build-script: build
    show-total: true
    collapse-unchanged: true
##[error]Cannot read property 'base' of undefined
```

Looking into the code, it appears to be because the action depends on `context.payload.pull_request`: https://github.com/preactjs/compressed-size-action/blob/6cd4d74bf28d472327aeebe8e71dbc903a85da7f/action.js#L23
which presumably doesn't exist on push-triggered workflows.

I wanted the action run on push because a PR can go through multiple iterations and I wanted the compressed size reported for every iteration.

Ideal would be to support both types of triggers (it appears there is some [commented out code](https://github.com/preactjs/compressed-size-action/blob/6cd4d74bf28d472327aeebe8e71dbc903a85da7f/action.js#L22) to use the octokit API to fetch PR data), but at the very least it would be nice to fail a bit more gracefully (with a clearer error message).

**Comment by developit** [comment]
I'd like to support push workflows here too. FWIW, when your PR goes through multiple iterations, you can see the history of each commit's builds by looking at Github's "edit history" for the size action comment. It holds a log of every size delta produced, each compared to the PR base. To me this seems preferable, since I rarely want to see each commit's delta from the previous commit.

**Comment by gavinsharp** [comment]
> FWIW, when your PR goes through multiple iterations, you can see the history of each commit's builds by looking at Github's "edit history" for the size action comment. It holds a log of every size delta produced, each compared to the PR base. To me this seems preferable, since I rarely want to see each commit's delta from the previous commit.

Hmm, I think I misunderstood how the `pull_request` trigger works. I assumed it only ran on PR creation.

**Comment by gavinsharp** [comment]
Thanks for the quick response!
