### ISSUE TITLE
Support `working_directory` option

### ISSUE THREAD

**Issue by stereobooster** [preactjs/compressed-size-action#64]
Hi, thanks for this action. My npm package is not in the root of the repo. 

WDYT about adding `working_directory` option - good idea or not?

**Comment by developit** [comment]
Seems like a reasonable feature!

**Comment by yhnavein** [comment]
@stereobooster `working_directory` support is missing, but you can use `cwd` instead. It works fine

```
- uses: preactjs/compressed-size-action@v2
  with:
    cwd: YOUR/DIR
```
