### ISSUE TITLE
add --legacy-peer-deps for npm install script

### ISSUE THREAD

**Issue by zombieJ** [preactjs/compressed-size-action#78]
Hi there,
Since our project has some external deps which config peerDeps but not really need that. Current build will failed since peer check. Please add `--legacy-peer-deps` mark or provide a config to enable ignore the peer check.

Thanks

**Comment by afc163** [comment]
+1

**Comment by developit** [comment]
This seems like a reasonable default to me.

**Comment by rschristian** [comment]
Probably well addressed in #85, so closing
