### ISSUE TITLE
Allow skipping install.

### ISSUE THREAD

**Issue by seivan** [preactjs/compressed-size-action#83]
Using zero-install PnP with yarn doesn't play well when intalling using `--frozen-lockfile`. 
Allow opting out of installing all together.

Don't mind doing the PR if it's ok.

**Comment by NateRadebaugh** [comment]
This feature would also help when npm deps require `npm ci --force` for the action to work. aka deps that still don't officially support react 18.x even though things may work fine.

**Comment by rschristian** [comment]
#85 probably addresses this reasonably, feel free to comment if there's something better we could land though
