### ISSUE TITLE
Size change always 0 Bytes

### ISSUE THREAD

**Issue by selankon** [preactjs/compressed-size-action#92]
Looking at this action (and any other on my project) the size change is always 0 B:

```
**Size Change:** 0 B 🆕

**Total Size:** 0 B
```

https://github.com/libremesh/lime-app/actions/runs/4828080867/jobs/8601485901?pr=370#step:4:332

The size on the current build for `index.html` is  `869 B`: 

https://github.com/libremesh/lime-app/actions/runs/4828080867/jobs/8601485901?pr=370#step:4:157

Instead for the base is `567 B`:

https://github.com/libremesh/lime-app/actions/runs/4828080867/jobs/8601485901?pr=370#step:4:291

Not sure if I' doing something bad? Is using node 16.

**Comment by rschristian** [comment]
Sorry for the long delay.

This looks to be operating correctly. Per [the docs](https://github.com/preactjs/compressed-size-action?tab=readme-ov-file#customizing-the-list-of-files), the default input pattern in `**/dist/**/*.js`. On the linked Preact-CLI app, it's building to `/build`, hence, the pattern won't match anything.

Customizing the input files is the correct action here:

```yml
with:
  pattern: "/build/**/*.js"
```
